version: '3.8'
services:
  main:
    image: busybox:musl
    command: >
      sh -c "sleep 30; true"
  consul:
    image: consul:1.8.1
  nomad:
    build:
      context: .
      dockerfile: Dockerfile.nomad
