version: '3.8'

networks:
  spark-on-nomad-test:
    driver: bridge

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks: ["spark-on-nomad-test"]
  cluster:
    image: consul:1.8.1
    networks: ["spark-on-nomad-test"]
    expose:
    - "4646"
    - "8500"
    - "8080"
  nomad:
    build:
      context: .
      dockerfile: Dockerfile.nomad
    network_mode: "service:cluster"
  k8s-emul:
    image: "${K8S_EMUL_IMAGE}"
    network_mode: "service:cluster"
