#!/bin/bash

set -euxo pipefail

retry() {
    local count=$1
    local delay=$2
    shift 2

    while ! "$@"; do
        if [ $((count--)) -eq 0 ]; then
            return 1
        fi
        sleep "$delay"
    done
}

retry_curl() {
    retry "$1" "$2" curl --silent --show-error --fail "$3"
}

retry_curl 10 2 http://cluster:8080/health
retry_curl 10 2 http://cluster:8500/v1/status/leader
retry_curl 10 2 http://cluster:4646/v1/status/leader
