FROM debian:stable-slim

# hadolint ignore=DL3008,DL3009
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    libcap-ng-utils \
    python3-pip \
    python3-setuptools

RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

WORKDIR /tmp
RUN curl -LO https://downloads.apache.org/spark/spark-3.0.0/spark-3.0.0-bin-hadoop3.2.tgz
RUN tar xf /tmp/spark-*.tgz -C /opt

COPY test-in-docker .
CMD ["./test-in-docker"]
