FROM debian:stable-slim

# hadolint ignore=DL3008,DL3009
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates libcap-ng-utils

WORKDIR /tmp
COPY test-in-docker .
CMD ["./test-in-docker"]
