#!/bin/bash

set -euxo pipefail

captest --text

retry() {
    local count=$1
    local delay=$2
    shift 2

    while ! "$@"; do
        if [ $((count--)) -eq 0 ]; then
            return 1
        fi
        sleep "$delay"
    done
}

retry_curl() {
    retry "$1" "$2" curl --silent --show-error --fail "$3"
}

retry_curl 10 2 http://cluster:8080/health
retry_curl 10 2 http://cluster:8500/v1/status/leader
retry_curl 10 2 http://cluster:4646/v1/status/leader

cat >test-job.json <<'_END_'
{
  "Job": {
    "ID": "test",
    "Name": "test",
    "Type": "service",
    "Priority": 50,
    "Datacenters": ["dc1"],
    "TaskGroups": [
      {
        "Name": "group1",
        "Count": 1,
        "Tasks": [
          {
            "Name": "task1",
            "Driver": "docker",
            "User": "",
            "Config": {
              "image": "pierrezemb/gostatic:latest",
              "args": [
                "-enable-health"
              ],
              "network_mode": "container:tests_cluster_1"
            },
            "Resources": {
              "CPU": 500,
              "MemoryMB": 256,
              "Networks": [
                {
                  "Device": "",
                  "CIDR": "",
                  "IP": "",
                  "MBits": 10,
                  "DynamicPorts": [
                  ]
                }
              ]
            },
            "Leader": false
          }
        ],
        "RestartPolicy": {
          "Interval": 300000000000,
          "Attempts": 10,
          "Delay": 25000000000,
          "Mode": "delay"
        },
        "ReschedulePolicy": {
          "Attempts": 10,
          "Delay": 30000000000,
          "DelayFunction": "exponential",
          "Interval": 36000000000000,
          "MaxDelay": 3600000000000,
          "Unlimited": false
        },
        "EphemeralDisk": {
          "SizeMB": 120
        }
      }
    ],
    "Update": {
      "MaxParallel": 1,
      "MinHealthyTime": 10000000000,
      "HealthyDeadline": 180000000000,
      "AutoRevert": false,
      "Canary": 0
    }
  }
}
_END_

curl --silent --show-error --fail -XPOST http://cluster:4646/v1/jobs --data @test-job.json
retry_curl 30 2 http://cluster:8043/health
