name: CI

on:
  pull_request:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.0
    - name: Pull Docker layer cache
      uses: satackey/action-docker-layer-caching@v0.0.5
      with:
        key: docker-layer-caching-${{ github.workflow }}-build-{hash}
        restore-keys: docker-layer-caching-${{ github.workflow }}-build-
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: kyryloshpytsyaprismai
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: kyryloshpytsyaprismai/k8s-emul
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true

  test:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: >
        echo ::set-env name=K8S_EMUL_IMAGE::kyryloshpytsyaprismai/k8s-emul:sha-${GITHUB_SHA::7}
    - name: Pull Docker images
      run: >
        cd tests &&
        docker-compose pull
    - name: Pull Docker layer cache
      uses: satackey/action-docker-layer-caching@v0.0.5
      with:
        key: docker-layer-caching-${{ github.workflow }}-test-{hash}
        restore-keys: docker-layer-caching-${{ github.workflow }}-test-
    - name: Run tests
      run: >
        sudo
        --preserve-env=K8S_EMUL_IMAGE
        ./run-tests
