name: CI

on:
  pull_request:
  push:
    branches: "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0

  test:
    needs:
    - pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo ./run-tests
