name: CI

on:
  pull_request:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/k8s-emul
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true

  test:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo ./run-tests
